version: '3.1'

services:

  app:
    build: ./
    ports: 
      - "5000:5000"
    restart: "no"
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
    ports:
      - "6603:3306"